name: list_space_settings
description: Get space settings
method: GET
endpoint: /wiki/rest/api/space/{spaceKey}/settings
template: search
tags:
- Space settings
params:
  required:
  - name: spaceKey
    type: string
    description: 'Path parameter: spaceKey'
  optional: []
template_config: {}
