name: get_k8s_cluster
endpoint: /v3.0/containerSecurity/kubernetesClusters/{cluster_id}
method: GET
template: single_get
description: Get Kubernetes cluster details
params:
  required:
  - name: cluster_id
    type: str
    description: Cluster ID
  optional: []
template_config:
  pagination: null
  date_params: null
  filter_style: null
categories:
- cloud_security
- container_security
