name: run_script
endpoint: /v3.0/response/customScripts/run
method: POST
template: post_action
description: Run script on endpoints
params:
  required:
  - name: script_id
    type: str
    description: Script ID
  - name: endpoint_guids
    type: list
    description: List of endpoint GUIDs
  optional:
  - name: parameters
    type: str
    description: Script parameters
    default: ''
template_config:
  pagination: null
  date_params: null
  filter_style: null
  body_builder: script_run
categories:
- response_actions
- incident_response
