name: response_containers_terminate
description: Terminate container
method: POST
endpoint: /v3.0/response/containers/terminate
template: response_action
tags:
- Container
params:
  required: []
  optional: []
template_config: {}
