name: list_response_isolated_traffic_exceptions
description: Get network traffic exceptions for isolated endpoints
method: GET
endpoint: /v3.0/response/isolatedTrafficExceptions
template: single_get
tags:
- Endpoint
params:
  required: []
  optional:
  - name: TMV1-Filter
    type: string
    description: 'Filter for retrieving a subset of the network traffic exceptions
      list.


      Supported fields:


      |Field     |Description                                                |Supported
      values                                 |

      |----------|-----------------------------------------------------------|-------------------------------------------------|

      |direction |The direction of network traffic of the traffic exception. |`inbound`,
      `outbound`                            |

      |ip        |The IP address of the traffic exception.                   |Any
      IPv4 address                                 |

      |protocol  |The network protocol of the traffic exception.             |`"Any"`,
      `"TCP/UDP"`, `"TCP"`, `"UDP"`, `"ICMP"` |

      |port      |The port numbers associated with the traffic exception.    |0-65535                                          |


      Supported operators:


      |Operator|Description|

      |-----|-----------|

      |`eq` |Operator ''equal to''|

      |`and`|Operator ''and''|

      |`or` |Operator ''or''|

      |`not`|Operator ''not''|

      |`()` |Symbols for grouping operands with their correct operator|

      '
template_config: {}
