name: get_cloud_asset
endpoint: /v3.0/asrm/attackSurfaceCloudAssets/{asset_id}
method: GET
template: single_get
description: Get cloud asset details
params:
  required:
  - name: asset_id
    type: str
    description: Asset ID
  optional: []
template_config:
  pagination: null
  date_params: null
  filter_style: null
categories:
- risk_management
- asset_inventory
