"""Backup {{NAMESPACE}} PVC data to S3 + Secrets Manager.

Auto-generated by eks-backup skill. Config: backup-config.yaml
"""
import json
import os
import subprocess
import time
import yaml

DATA_DIR = os.environ.get("DATA_DIR", "/data")
AWS_PROFILES = os.environ.get("AWS_PROFILES", "{{AWS_PROFILES}}").split(",")
SECRET_NAME = "{{SECRET_NAME}}"
BUCKET_PREFIX = "{{BUCKET_PREFIX}}"
DATA_PATHS = {{DATA_PATHS_JSON}}

# Load config if available (overrides defaults)
_cfg_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "backup-config.yaml")
if os.path.isfile(_cfg_path):
    with open(_cfg_path) as _f:
        _cfg = yaml.safe_load(_f)
    AWS_PROFILES = [a["profile"] for a in _cfg.get("aws_accounts", [])]
    SECRET_NAME = _cfg.get("secret_name", SECRET_NAME)
    BUCKET_PREFIX = _cfg.get("bucket_prefix", BUCKET_PREFIX)
    DATA_PATHS = _cfg.get("data_paths", DATA_PATHS)


def run(cmd, profile=None, timeout=60):
    env = os.environ.copy()
    if profile and profile != "default":
        env["AWS_PROFILE"] = profile
    r = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=timeout)
    return r.returncode, r.stdout.strip(), r.stderr.strip()


def get_bucket(profile):
    code, out, _ = run(["aws", "sts", "get-caller-identity", "--query", "Account", "--output", "text"], profile)
    return f"{BUCKET_PREFIX}-{out.strip()}" if code == 0 else None


def main():
    ts = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    print(f"=== Backup started at {ts} ===")

    for profile in AWS_PROFILES:
        profile = profile.strip()
        print(f"\n--- {profile} ---")
        bucket = get_bucket(profile)
        if not bucket:
            print(f"  SKIP: cannot auth")
            continue

        for path in DATA_PATHS:
            local = os.path.join(DATA_DIR, path)
            if os.path.isdir(local):
                code, _, err = run(["aws", "s3", "sync", local, f"s3://{bucket}/{path}", "--delete"], profile, 120)
                print(f"  {path}: {'ok' if code == 0 else err[:80]}")
            elif os.path.isfile(local):
                code, _, err = run(["aws", "s3", "cp", local, f"s3://{bucket}/{path}"], profile)
                print(f"  {path}: {'ok' if code == 0 else err[:80]}")

        # Backup refresh token
        rt_path = os.path.join(DATA_DIR, "refresh_token")
        if os.path.isfile(rt_path):
            with open(rt_path) as f:
                rt = f.read().strip()
            if rt:
                code, _, _ = run(["aws", "secretsmanager", "put-secret-value",
                    "--secret-id", SECRET_NAME,
                    "--secret-string", json.dumps({"refresh_token": rt})], profile)
                print(f"  secret: {'ok' if code == 0 else 'failed'}")

        # Marker
        marker = json.dumps({"timestamp": ts, "profile": profile, "bucket": bucket})
        marker_path = os.path.join(DATA_DIR, f".backup-marker-{profile}.json")
        with open(marker_path, "w") as f:
            f.write(marker)
        run(["aws", "s3", "cp", marker_path, f"s3://{bucket}/backup-markers/{profile}.json"], profile)

    print(f"\n=== Done ===")


if __name__ == "__main__":
    main()
