"""Restore {{NAMESPACE}} from AWS backups.

Auto-generated by eks-backup skill. Config: backup-config.yaml
"""
import argparse
import json
import os
import subprocess
import sys
import time
import yaml

BUCKET_PREFIX = "{{BUCKET_PREFIX}}"
SECRET_NAME = "{{SECRET_NAME}}"
DATA_PATHS = {{DATA_PATHS_JSON}}

_cfg_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "backup-config.yaml")
if os.path.isfile(_cfg_path):
    with open(_cfg_path) as _f:
        _cfg = yaml.safe_load(_f)
    BUCKET_PREFIX = _cfg.get("bucket_prefix", BUCKET_PREFIX)
    SECRET_NAME = _cfg.get("secret_name", SECRET_NAME)
    DATA_PATHS = _cfg.get("data_paths", DATA_PATHS)


def run(cmd, profile=None, timeout=60):
    env = os.environ.copy()
    if profile and profile != "default":
        env["AWS_PROFILE"] = profile
    r = subprocess.run(cmd, capture_output=True, text=True, env=env, timeout=timeout)
    return r.returncode, r.stdout.strip(), r.stderr.strip()


def get_bucket(profile):
    code, out, _ = run(["aws", "sts", "get-caller-identity", "--query", "Account", "--output", "text"], profile)
    return f"{BUCKET_PREFIX}-{out.strip()}" if code == 0 else None


def main():
    parser = argparse.ArgumentParser(description="Restore {{NAMESPACE}} from AWS backups")
    parser.add_argument("--target", default="./restored", help="Directory to restore to")
    parser.add_argument("--profile", default="default", help="AWS profile")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    print(f"=== Restore {{NAMESPACE}} ===")
    print(f"  Target:  {os.path.abspath(args.target)}")
    print(f"  Profile: {args.profile}")
    print(f"  Dry run: {args.dry_run}")

    bucket = get_bucket(args.profile)
    if not bucket:
        print("ERROR: Cannot reach AWS")
        sys.exit(1)

    code, _, _ = run(["aws", "s3", "ls", f"s3://{bucket}/"], args.profile)
    if code != 0:
        print(f"ERROR: Bucket {bucket} not found")
        sys.exit(1)

    print(f"  Bucket: {bucket}\n")
    target = args.target

    for path in DATA_PATHS:
        s3_uri = f"s3://{bucket}/{path}"
        local = os.path.join(target, path)

        if args.dry_run:
            code, out, _ = run(["aws", "s3", "ls", s3_uri, "--recursive", "--summarize"], args.profile)
            count = out.count("\n") if code == 0 else 0
            print(f"  {path}: {count} objects")
        else:
            os.makedirs(os.path.dirname(local) if "." in os.path.basename(path) else local, exist_ok=True)
            if "." in os.path.basename(path):
                code, _, err = run(["aws", "s3", "cp", s3_uri, local], args.profile)
            else:
                code, _, err = run(["aws", "s3", "sync", s3_uri, local], args.profile, 120)
            print(f"  {path}: {'ok' if code == 0 else 'not found'}")

    # Restore secret
    code, out, _ = run(["aws", "secretsmanager", "get-secret-value",
        "--secret-id", SECRET_NAME, "--query", "SecretString", "--output", "text"], args.profile)
    if code == 0:
        try:
            rt = json.loads(out).get("refresh_token", "")
            if rt and rt != "PLACEHOLDER":
                if args.dry_run:
                    print(f"  secret: exists ({len(rt)} chars)")
                else:
                    os.makedirs(target, exist_ok=True)
                    with open(os.path.join(target, "refresh_token"), "w") as f:
                        f.write(rt)
                    print(f"  secret: restored")
        except json.JSONDecodeError:
            print(f"  secret: invalid JSON")
    else:
        print(f"  secret: not found")

    if not args.dry_run:
        with open(os.path.join(target, ".restored.json"), "w") as f:
            json.dump({"timestamp": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                       "profile": args.profile, "bucket": bucket}, f, indent=2)
        print(f"\n  Restored to {os.path.abspath(target)}/")


if __name__ == "__main__":
    main()
