name: list_asrm_cloud_vm_vulnerabilities
description: Get vulnerabilities in cloud VMs
method: GET
endpoint: /v3.0/asrm/cloudVmVulnerabilities
template: standard_list
tags:
- Risk Factors
params:
  required: []
  optional:
  - name: TMV1-Filter
    type: string
    description: 'Filter for retrieving a subset of the highly-exploitable CVEs detected
      in your cloud VMs


      Supported fields:


      | Field                        | Description                                                  |
      Supported values        |

      | ---------------------------- | ------------------------------------------------------------
      | ----------------------- |

      | `cveId`                      | The Common Vulnerabilities and Exposures identifier
      (CVE ID) | Any value               |

      | `cveRiskLevel`               | The risk level of the risk event triggered
      by the CVE        | `high`, `medium`, `low` |

      | `globalExploitActivityLevel` | Indicates how often attackers are exploiting
      a vulnerability | `high`, `medium`, `low` |

      | `firstSeenDateTime`          | The date the CVE was first detected in your
      environment      | Any value               |

      | `publishedDateTime`          | The date MITRE published the CVE                             |
      Any value               |


      Supported operators:


      | Operator | Description                       | Notes                                                          |

      | -------- | --------------------------------- | --------------------------------------------------------------
      |

      | `eq`     | Operator `equal to`.              | -                                                              |

      | `gt`     | Operator `greater than`.          | Only applicable to `firstSeenDateTime`
      and `publishedDateTime` |

      | `ge`     | Operator `greater than or equal`. | Only applicable to `firstSeenDateTime`
      and `publishedDateTime` |

      | `le`     | Operator `less than or equal`.    | Only applicable to `firstSeenDateTime`
      and `publishedDateTime` |

      | `lt`     | Operator `less than`.             | Only applicable to `firstSeenDateTime`
      and `publishedDateTime` |

      | `and`    | Operator `and`.                   | -                                                              |

      | `or`     | Operator `or`.                    | -                                                              |

      | `not`    | Operator `not`.                   | -                                                              |

      | `( )`    | Symbols for grouping operands.    | -                                                              |

      '
  - name: orderBy
    type: string
    description: 'The field by which the results are sorted.


      To display records in ascending or descending order, add the phrase `asc` or
      `desc` after the parameter name.


      Available values:

      * `cveRiskLevel`

      '
  - name: top
    type: integer
    description: 'The number of records displayed on a page

      '
template_config:
  pagination:
    param: top
    type: int
    max: 200
