name: list_response_osquery_statements
description: List osquery statements
method: GET
endpoint: /v3.0/response/osqueryStatements
template: standard_list
tags:
- osquery
params:
  required: []
  optional:
  - name: top
    type: string
    description: ''
template_config:
  pagination:
    param: top
    type: int
    max: 200
