"""
Screenshot Test Template
Runs in mcr.microsoft.com/playwright/python container.
Customize PAGES list for your project.
Generated by gh-ci-setup skill
"""

import json
import sys
import time
from pathlib import Path

from playwright.sync_api import sync_playwright

BASE_URL = "{{BASE_URL}}"
OUTPUT_DIR = Path("/output")
VIEWPORT = {"width": 1280, "height": 900}

# Customize: login credentials (set to None to skip login)
LOGIN_URL = "{{LOGIN_URL}}"  # e.g., "/login"
LOGIN_DATA = {{LOGIN_DATA}}  # e.g., {"username": "admin", "password": "secret"}

# Customize: pages to screenshot
PAGES = [
    # ("01", "filename", "/url-path", "Description"),
    {{PAGES_LIST}}
]


def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    results = []
    exit_code = 0

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(viewport=VIEWPORT, ignore_https_errors=True)
        page = context.new_page()

        # Login if configured
        if LOGIN_URL and LOGIN_DATA:
            try:
                page.goto(f"{BASE_URL}{LOGIN_URL}", wait_until="networkidle", timeout=30000)
                for field, value in LOGIN_DATA.items():
                    page.fill(f'input[name="{field}"]', value)
                page.click('input[type="submit"], button[type="submit"]')
                page.wait_for_load_state("networkidle", timeout=30000)
                time.sleep(2)
                print("Login successful.\n")
            except Exception as e:
                print(f"Login failed: {e}")

        # Take screenshots
        for num, name, url_path, desc in PAGES:
            filename = f"{num}-{name}.png"
            try:
                page.goto(f"{BASE_URL}{url_path}", wait_until="networkidle", timeout=30000)
                time.sleep(1)
                page.screenshot(path=str(OUTPUT_DIR / filename), full_page=True)
                results.append({"num": num, "name": name, "file": filename, "desc": desc, "status": "OK"})
                print(f"OK    {filename:40s} {desc}")
            except Exception as e:
                try:
                    page.screenshot(path=str(OUTPUT_DIR / filename), full_page=True)
                    results.append({"num": num, "name": name, "file": filename, "desc": desc, "status": "ERROR_CAPTURED", "error": str(e)})
                    print(f"WARN  {filename:40s} {desc} (error captured)")
                except Exception:
                    results.append({"num": num, "name": name, "file": filename, "desc": desc, "status": "ERROR", "error": str(e)})
                    print(f"ERROR {filename:40s} {desc}: {e}")
                    exit_code = 1

        browser.close()

    with open(OUTPUT_DIR / "results.json", "w") as f:
        json.dump(results, f, indent=2)

    ok = sum(1 for r in results if r["status"] == "OK")
    print(f"\nScreenshots: {ok}/{len(results)} OK")
    return exit_code


if __name__ == "__main__":
    sys.exit(main())
