#!/bin/bash
# =============================================================================
# Test Orchestrator Template
# Runs functional tests + screenshot tests, generates report.
# Generated by gh-ci-setup skill
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
RESULTS_DIR="${PROJECT_DIR}/test-results"
SCREENSHOTS_DIR="${RESULTS_DIR}/screenshots"
CONTAINER_NAME="{{CONTAINER_NAME}}"
NETWORK_NAME="{{NETWORK_NAME}}"
PLAYWRIGHT_IMAGE="mcr.microsoft.com/playwright/python:latest"

mkdir -p "$RESULTS_DIR" "$SCREENSHOTS_DIR"

echo "=== {{PROJECT_NAME}} Test Suite ==="
echo "Time: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
echo ""

# --- Pre-flight ---
echo "--- Pre-flight ---"
if ! docker inspect "$CONTAINER_NAME" --format '{{.State.Status}}' 2>/dev/null | grep -q running; then
    echo "FATAL: Container $CONTAINER_NAME is not running."
    exit 1
fi
health=$(docker inspect "$CONTAINER_NAME" --format '{{.State.Health.Status}}' 2>/dev/null || echo "unknown")
echo "Container: $CONTAINER_NAME ($health)"

if ! docker network inspect "$NETWORK_NAME" >/dev/null 2>&1; then
    NETWORK_NAME=$(docker inspect "$CONTAINER_NAME" --format '{{range $k,$v := .NetworkSettings.Networks}}{{$k}}{{end}}' 2>/dev/null | head -1)
fi
echo "Network: $NETWORK_NAME"
echo ""

# --- Tier 1: Functional Tests ---
echo "=== Functional Tests ==="
docker cp "${PROJECT_DIR}/tests/functional/test-all.sh" "${CONTAINER_NAME}:/tmp/test-all.sh"
docker exec "$CONTAINER_NAME" chmod +x /tmp/test-all.sh
FUNC_EXIT=0
docker exec "$CONTAINER_NAME" bash /tmp/test-all.sh 2>&1 | tee "${RESULTS_DIR}/functional.log" || FUNC_EXIT=$?
docker cp "${CONTAINER_NAME}:/tmp/test-results.json" "${RESULTS_DIR}/functional-results.json" 2>/dev/null || true
echo ""

# --- Tier 2: Screenshot Tests ---
echo "=== Screenshot Tests ==="
SCREENSHOT_EXIT=0
docker run --rm \
    --network "$NETWORK_NAME" \
    -v "${PROJECT_DIR}/tests/screenshots/playwright-screenshots.py:/tests/playwright-screenshots.py:ro" \
    -v "${SCREENSHOTS_DIR}:/output" \
    "$PLAYWRIGHT_IMAGE" \
    python /tests/playwright-screenshots.py 2>&1 | tee "${RESULTS_DIR}/screenshots.log" || SCREENSHOT_EXIT=$?
[ -f "${SCREENSHOTS_DIR}/results.json" ] && cp "${SCREENSHOTS_DIR}/results.json" "${RESULTS_DIR}/screenshot-results.json"
echo ""

# --- Generate Report ---
echo "=== Generating Report ==="
REPORT="${RESULTS_DIR}/REPORT.md"
echo "# {{PROJECT_NAME}} Test Report" > "$REPORT"
echo "" >> "$REPORT"
echo "**Generated**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$REPORT"
echo "**Container**: ${CONTAINER_NAME} (${health})" >> "$REPORT"
echo "" >> "$REPORT"

# Functional results
echo "## Functional Tests" >> "$REPORT"
echo "" >> "$REPORT"
if [ -f "${RESULTS_DIR}/functional-results.json" ]; then
    python3 - "${RESULTS_DIR}/functional-results.json" >> "$REPORT" << 'PYSCRIPT'
import json, sys
with open(sys.argv[1]) as f:
    results = json.load(f)
p = sum(1 for r in results if r['status'] == 'PASS')
f = sum(1 for r in results if r['status'] == 'FAIL')
x = sum(1 for r in results if r['status'] == 'XFAIL')
print(f"**Results**: {p} passed, {f} failed, {x} expected-fail\n")
print("| Status | Test | Description |")
print("|--------|------|-------------|")
for r in results:
    icon = {"PASS": "PASS", "FAIL": "**FAIL**", "XFAIL": "XFAIL"}[r['status']]
    print(f"| {icon} | `{r['name']}` | {r['description']} |")
print()
PYSCRIPT
fi

# Screenshot results
echo "## Screenshots" >> "$REPORT"
echo "" >> "$REPORT"
if [ -f "${RESULTS_DIR}/screenshot-results.json" ]; then
    python3 - "${RESULTS_DIR}/screenshot-results.json" >> "$REPORT" << 'PYSCRIPT'
import json, sys
with open(sys.argv[1]) as f:
    results = json.load(f)
for r in results:
    fname = r.get('file', '')
    if fname:
        print(f"### {r['num']}. {r['desc']}\n")
        print(f"![{r['desc']}](screenshots/{fname})\n")
PYSCRIPT
fi

echo "Report written to: ${REPORT}"

echo ""
echo "========================================"
if [ "$FUNC_EXIT" -eq 0 ] && [ "$SCREENSHOT_EXIT" -eq 0 ]; then
    echo "ALL TESTS PASSED"
    exit 0
else
    echo "SOME TESTS FAILED (functional=$FUNC_EXIT, screenshots=$SCREENSHOT_EXIT)"
    exit 1
fi
