#!/bin/bash
# =============================================================================
# CI Setup Template
# Collects credentials, pushes GitHub secrets, registers runner
# Generated by gh-ci-setup skill
# =============================================================================
set -euo pipefail

echo "=== {{PROJECT_NAME}} CI Setup ==="
echo ""

REPO=$(gh repo view --json nameWithOwner -q '.nameWithOwner' 2>/dev/null || true)
if [ -z "$REPO" ]; then
    echo "ERROR: Not in a GitHub repository or gh CLI not authenticated."
    echo "Run: gh auth login"
    exit 1
fi
echo "Repository: $REPO"
echo ""

# =============================================================================
# [1/4] Collect credentials
# =============================================================================
echo "[1/4] Collecting credentials..."
echo ""

read -rsp "  Enter Anthropic API key (for Claude Code auto-fix): " ANTHROPIC_KEY
echo ""

read -rp "  Enter notification email for CI failures: " NOTIFY_EMAIL

echo ""
read -rp "  Configure SMTP for email notifications? [y/N]: " CONFIGURE_SMTP
SMTP_SERVER="" SMTP_USERNAME="" SMTP_PASSWORD=""
if [[ "$CONFIGURE_SMTP" =~ ^[Yy] ]]; then
    read -rp "    SMTP server: " SMTP_SERVER
    read -rp "    SMTP username: " SMTP_USERNAME
    read -rsp "    SMTP password: " SMTP_PASSWORD
    echo ""
fi

echo ""

# =============================================================================
# [2/4] Push secrets to GitHub
# =============================================================================
echo "[2/4] Pushing secrets to GitHub..."

push_secret() {
    local name="$1" value="$2"
    if [ -n "$value" ]; then
        echo "$value" | gh secret set "$name" --repo "$REPO"
        echo "  -> $name: set"
    fi
}

push_secret "ANTHROPIC_API_KEY" "${ANTHROPIC_KEY:-}"
push_secret "NOTIFY_EMAIL" "${NOTIFY_EMAIL:-}"
push_secret "SMTP_SERVER" "${SMTP_SERVER:-}"
push_secret "SMTP_USERNAME" "${SMTP_USERNAME:-}"
push_secret "SMTP_PASSWORD" "${SMTP_PASSWORD:-}"

echo ""

# =============================================================================
# [3/4] Self-hosted runner (optional)
# =============================================================================
echo "[3/4] Self-hosted runner..."

RUNNER_COUNT=$(gh api "repos/${REPO}/actions/runners" --jq '.total_count' 2>/dev/null || echo "0")
if [ "$RUNNER_COUNT" -gt 0 ]; then
    echo "  -> Runner already registered ($RUNNER_COUNT found)"
else
    echo "  -> No runner registered. Set up at:"
    echo "     https://github.com/${REPO}/settings/actions/runners/new"
fi

echo ""

# =============================================================================
# [4/4] Verification
# =============================================================================
echo "[4/4] Verification..."

SECRET_COUNT=$(gh secret list --repo "$REPO" 2>/dev/null | wc -l)
echo "  -> Secrets: $SECRET_COUNT configured"

if docker info >/dev/null 2>&1; then
    echo "  -> Docker: accessible"
else
    echo "  -> Docker: NOT accessible"
fi

echo ""
echo "Setup complete. Push a commit to trigger the CI pipeline."
