#!/bin/bash
# =============================================================================
# Docker Container Functional Test Template
# Runs inside a container via docker exec.
# Customize the sections below for your project.
# Generated by gh-ci-setup skill
# =============================================================================
set -o pipefail

PASS_COUNT=0
FAIL_COUNT=0
XFAIL_COUNT=0
TOTAL=0
RESULTS_JSON="[]"

# --- Config (customize these) ---
BASE_URL="{{BASE_URL}}"
HEALTH_URL="{{HEALTH_URL}}"
CURL_OPTS="-sk --connect-timeout 5 --max-time 10"
XFAIL_PAGES="{{XFAIL_PAGES}}"

# --- Helpers ---
record() {
    local status="$1" name="$2" desc="$3"
    TOTAL=$((TOTAL + 1))
    case "$status" in
        PASS)  PASS_COUNT=$((PASS_COUNT + 1));  printf "PASS   %-35s %s\n" "$name" "$desc" ;;
        FAIL)  FAIL_COUNT=$((FAIL_COUNT + 1));  printf "FAIL   %-35s %s\n" "$name" "$desc" ;;
        XFAIL) XFAIL_COUNT=$((XFAIL_COUNT + 1)); printf "XFAIL  %-35s %s\n" "$name" "$desc" ;;
    esac
    RESULTS_JSON=$(echo "$RESULTS_JSON" | python3 -c "
import sys, json
arr = json.load(sys.stdin)
arr.append({'status':'$status','name':'$name','description':'$desc'})
json.dump(arr, sys.stdout)
")
}

is_xfail() {
    echo "$XFAIL_PAGES" | grep -qw "$1"
}

# =============================================================================
# SECTION A: Service Health
# =============================================================================
echo ""
echo "=== A. Service Health ==="

# A1: Health endpoint
http_code=$(curl $CURL_OPTS -o /dev/null -w '%{http_code}' "${HEALTH_URL}/health")
if [ "$http_code" = "200" ]; then
    record PASS health_endpoint "Health endpoint returns 200"
else
    record FAIL health_endpoint "Health endpoint HTTP $http_code"
fi

# Add project-specific health checks here...

# =============================================================================
# SECTION B: Web Pages (if applicable)
# =============================================================================
echo ""
echo "=== B. Web Pages ==="

# Add page-specific checks here...

# =============================================================================
# SECTION C: Database (if applicable)
# =============================================================================
echo ""
echo "=== C. Database ==="

# Add database-specific checks here...

# =============================================================================
# Summary
# =============================================================================
echo ""
echo "========================================"
echo "RESULTS: $PASS_COUNT passed, $FAIL_COUNT failed, $XFAIL_COUNT expected-fail (total: $TOTAL)"
echo "========================================"

echo "$RESULTS_JSON" | python3 -m json.tool > /tmp/test-results.json 2>/dev/null || \
    echo "$RESULTS_JSON" > /tmp/test-results.json

[ "$FAIL_COUNT" -eq 0 ] && exit 0 || exit 1
