name: list_asrm_vulnerabilities_affected_serverless_function_layers
description: Get serverless function layers affected by CVEs
method: GET
endpoint: /v3.0/asrm/vulnerabilities/{id}/affectedServerlessFunctionLayers
template: standard_list
tags:
- Threat and Exposure Management
params:
  required:
  - name: id
    type: string
    description: The CVE ID
  optional:
  - name: top
    type: integer
    description: 'The number of records displayed on a page


      Default: `100`

      '
template_config:
  pagination:
    param: top
    type: int
    max: 200
