name: list_analytics_content_views
description: Get views
method: GET
endpoint: /wiki/rest/api/analytics/content/{contentId}/views
template: search
tags:
- Analytics
params:
  required:
  - name: contentId
    type: string
    description: 'Path parameter: contentId'
  optional: []
template_config: {}
