name: update_case_management_cases_contents
description: Update the case content
method: PATCH
endpoint: /v3.0/caseManagement/cases/{id}/contents/{contentId}
template: patch_update
tags:
- Case
params:
  required:
  - name: id
    type: string
    description: The case ID
  - name: contentId
    type: string
    description: The content ID
  optional:
  - name: If-Match
    type: string
    description: Provide the ETag of the resource to be updated
template_config: {}
