#!/usr/bin/env node
/**
 * poll-sources.js — Polls all data sources and updates local cache files.
 * Part of the weekly-data skill. Reads config.json for paths (auto-generated by setup.js).
 *
 * Usage:
 *   node poll-sources.js              # Poll all sources
 *   node poll-sources.js --source emails   # Poll one source
 *   node poll-sources.js --since 2026-03-24  # Override start date
 *   node poll-sources.js --dry-run    # Show what would be fetched
 *
 * Sources: emails, cases, calendar, teams, transcripts, notes
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const SKILL_DIR = __dirname;
const CONFIG_FILE = path.join(SKILL_DIR, 'config.json');

// ─── Config ───────────────────────────────────────────────────────

function loadConfig() {
  if (!fs.existsSync(CONFIG_FILE)) {
    console.error('No config.json found. Run setup first: node setup.js');
    process.exit(1);
  }
  return JSON.parse(fs.readFileSync(CONFIG_FILE, 'utf-8'));
}

const config = loadConfig();
const MSGRAPH_LIB = config.msgraphLib;
const TEAMS_CHAT = config.teamsChat;
const PROJECT_ROOT = config.projectRoot;
const NOTES_DIRS = config.notesDirs || [];
const TEAMS_TARGETS = config.teamsTargets || {
  'Squad 1': 'squad1', 'SPG - Internal': 'internal',
  'SPG - External': 'external'
};

// ─── Helpers ──────────────────────────────────────────────────────

function getWeekDir() {
  const now = new Date();
  const day = now.getDay();
  const fri = new Date(now);
  fri.setDate(now.getDate() + (5 - (day === 0 ? 7 : day)));
  return path.join(PROJECT_ROOT, 'reports', 'weekly-data', fri.toISOString().slice(0, 10));
}

function getMonday() {
  const now = new Date();
  const day = now.getDay();
  const monday = new Date(now);
  monday.setDate(now.getDate() - (day === 0 ? 6 : day - 1));
  return monday.toISOString().slice(0, 10);
}

function ensureDirs(weekDir) {
  fs.mkdirSync(path.join(weekDir, 'sources'), { recursive: true });
  fs.mkdirSync(path.join(weekDir, 'corrections'), { recursive: true });
  for (const f of ['terminology.md', 'customers.md', 'style.md']) {
    const p = path.join(weekDir, 'corrections', f);
    if (!fs.existsSync(p)) {
      const name = f.replace('.md', '');
      fs.writeFileSync(p, `# ${name.charAt(0).toUpperCase() + name.slice(1)} Corrections\n\nEdit this file to correct how summaries interpret your data.\n\n`);
    }
  }
}

// ─── Edit Preservation ────────────────────────────────────────────
// When refreshing source files, preserve any "My read:", "Relevant?",
// or "My takeaways" content the user has edited.

function extractUserEdits(filePath) {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, 'utf-8');
  const edits = {};

  // Parse sections by ## heading
  const sections = content.split(/^## /m).slice(1);
  for (const section of sections) {
    const headingLine = section.split('\n')[0].trim();
    // Extract key from heading (timestamp + subject)
    const key = headingLine;

    // Find "My read:" content
    const readMatch = section.match(/\*\*My read:\*\*\s*(.+?)(?=\n(?:\*\*|---|##|$))/s);
    if (readMatch && readMatch[1].trim()) {
      edits[key] = { type: 'read', value: readMatch[1].trim() };
    }

    // Find "Relevant?" content
    const relevantMatch = section.match(/\*\*Relevant\?\*\*\s*(.+?)(?=\n(?:- |\*\*|---|##|$))/s);
    if (relevantMatch && relevantMatch[1].trim()) {
      edits[key] = { type: 'relevant', value: relevantMatch[1].trim() };
    }
  }

  // Find "My takeaways" section (Teams files)
  const takeawaysMatch = content.match(/## My takeaways\n\n([\s\S]*?)$/);
  if (takeawaysMatch) {
    const val = takeawaysMatch[1].replace(/<!--.*?-->/g, '').trim();
    if (val) edits['__takeaways__'] = { type: 'takeaways', value: val };
  }

  return edits;
}

function applyUserEdits(newContent, edits, fileType) {
  if (Object.keys(edits).length === 0) return newContent;

  let result = newContent;

  for (const [key, edit] of Object.entries(edits)) {
    if (edit.type === 'takeaways') {
      // Replace the empty takeaways section
      result = result.replace(
        /## My takeaways\n\n<!-- Edit this section.*?-->\n/,
        `## My takeaways\n\n${edit.value}\n`
      );
      continue;
    }

    if (edit.type === 'read') {
      // Find the section with this heading and fill in "My read:"
      const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const re = new RegExp(`(## ${escaped}[\\s\\S]*?\\*\\*My read:\\*\\*) `, 'm');
      result = result.replace(re, `$1 ${edit.value}`);
    }

    if (edit.type === 'relevant') {
      const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const re = new RegExp(`(${escaped}[\\s\\S]*?\\*\\*Relevant\\?\\*\\*) `, 'm');
      result = result.replace(re, `$1 ${edit.value}`);
    }
  }

  return result;
}

function writeWithPreservedEdits(filePath, newContent) {
  const edits = extractUserEdits(filePath);
  const merged = applyUserEdits(newContent, edits);
  fs.writeFileSync(filePath, merged);
  const editCount = Object.keys(edits).length;
  if (editCount > 0) console.log(`    [preserved ${editCount} user edits]`);
}

function pythonQuery(script) {
  const tmpFile = path.join(SKILL_DIR, '.tmp-poll-query.py');
  try {
    fs.writeFileSync(tmpFile, script);
    return execSync(`python -u "${tmpFile}"`, {
      cwd: MSGRAPH_LIB,
      encoding: 'utf-8',
      env: { ...process.env, PYTHONIOENCODING: 'utf-8' },
      timeout: 30000
    });
  } catch (e) {
    console.error(`  [ERROR] ${e.message.slice(0, 200)}`);
    return '';
  } finally {
    try { fs.unlinkSync(tmpFile); } catch (_) {}
  }
}

// ─── Pollers ──────────────────────────────────────────────────────

function pollSentEmails(sourcesDir, since) {
  console.log('[emails] Polling sent emails...');
  const script = `
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, '.')
from token_manager import graph_get
data = graph_get('/me/mailFolders/sentitems/messages', params={
    '$top': '50',
    '$select': 'subject,toRecipients,sentDateTime,bodyPreview',
    '$orderby': 'sentDateTime desc',
    '$filter': "sentDateTime ge ${since}T00:00:00Z"
})
for m in data.get('value', []):
    subj = m.get('subject','')
    if any(x in subj.lower() for x in ['accepted:', 'declined:', 'tentatively accepted:']):
        continue
    to_list = ', '.join([r['emailAddress']['address'] for r in m.get('toRecipients',[])])
    preview = m.get('bodyPreview','')[:300].replace('\\n',' ').replace('|','-')
    dt = m['sentDateTime'][:16]
    print(f'{dt}|||{to_list}|||{subj}|||{preview}')
`;
  const raw = pythonQuery(script);
  if (!raw.trim()) return;

  const lines = raw.trim().split('\n').filter(l => l.includes('|||'));
  let md = `# Sent Emails\nLast polled: ${new Date().toISOString().slice(0, 19)}\nSince: ${since}\n\n`;
  for (const line of lines) {
    const [dt, to, subj, preview] = line.split('|||');
    md += `## ${dt} — ${subj}\n**To:** ${to}\n**Preview:** ${preview}\n**My read:** \n\n---\n\n`;
  }
  writeWithPreservedEdits(path.join(sourcesDir, 'sent-emails.md'), md);
  console.log(`  [OK] ${lines.length} emails`);
}

function pollCaseUpdates(sourcesDir, since) {
  console.log('[cases] Polling case updates...');
  const script = `
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, '.')
from token_manager import graph_get
folders = graph_get('/me/mailFolders', params={'$top': '50'})
fid = None
for f in folders.get('value', []):
    if 'case' in f.get('displayName','').lower():
        fid = f['id']
        break
if not fid:
    print('NO_FOLDER')
    sys.exit(0)
data = graph_get(f'/me/mailFolders/{fid}/messages', params={
    '$top': '50',
    '$select': 'subject,from,receivedDateTime,bodyPreview',
    '$orderby': 'receivedDateTime desc',
    '$filter': f"receivedDateTime ge ${since}T00:00:00Z"
})
for m in data.get('value', []):
    fr = m.get('from',{}).get('emailAddress',{}).get('address','')
    preview = m.get('bodyPreview','')[:200].replace('\\n',' ').replace('|','-')
    dt = m['receivedDateTime'][:16]
    subj = m.get('subject','')
    print(f'{dt}|||{fr}|||{subj}|||{preview}')
`;
  const raw = pythonQuery(script);
  if (!raw.trim() || raw.includes('NO_FOLDER')) return;

  const lines = raw.trim().split('\n').filter(l => l.includes('|||'));
  let md = `# Case Updates\nLast polled: ${new Date().toISOString().slice(0, 19)}\nSince: ${since}\n\n`;
  for (const line of lines) {
    const [dt, from, subj] = line.split('|||');
    const caseMatch = subj.match(/TM-\d+/);
    const caseNum = caseMatch ? caseMatch[0] : 'unknown';
    const custMatch = subj.match(/from ([\w\s,.]+?)$/);
    const customer = custMatch ? custMatch[1].trim() : '';
    md += `## ${dt} — ${caseNum}${customer ? ` (${customer})` : ''}\n**Subject:** ${subj}\n**From:** ${from}\n**My read:** \n\n---\n\n`;
  }
  writeWithPreservedEdits(path.join(sourcesDir, 'case-updates.md'), md);
  console.log(`  [OK] ${lines.length} cases`);
}

function pollCalendar(sourcesDir) {
  console.log('[calendar] Polling calendar...');
  const now = new Date();
  const twoWeeks = new Date(now);
  twoWeeks.setDate(now.getDate() + 14);

  const script = `
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, '.')
from token_manager import graph_get
data = graph_get('/me/calendarView', params={
    '$top': '80',
    '$select': 'subject,start,end,organizer,attendees,isAllDay',
    '$orderby': 'start/dateTime',
    'startDateTime': '${now.toISOString()}',
    'endDateTime': '${twoWeeks.toISOString()}'
})
for e in data.get('value', []):
    allday = '1' if e.get('isAllDay') else '0'
    start = e['start']['dateTime'][:16]
    end = e['end']['dateTime'][:16]
    org = e.get('organizer',{}).get('emailAddress',{}).get('name','')
    subj = e.get('subject','').replace('|','-')
    print(f'{allday}|||{start}|||{end}|||{subj}|||{org}')
`;
  const raw = pythonQuery(script);
  if (!raw.trim()) return;

  const lines = raw.trim().split('\n').filter(l => l.includes('|||'));
  let allDay = [], timed = [];
  for (const line of lines) {
    const [isAllDay, start, end, subj, org] = line.split('|||');
    (isAllDay === '1' ? allDay : timed).push({ start, end, subj, org });
  }

  let md = `# Calendar\nLast polled: ${new Date().toISOString().slice(0, 19)}\n\n## All-Day Events\n\n`;
  if (!allDay.length) md += `None.\n\n`;
  for (const e of allDay) {
    md += `- **${e.start.slice(0,10)} to ${e.end.slice(0,10)}** — ${e.subj} (Org: ${e.org})\n  **Relevant?** \n`;
  }
  md += `\n## Scheduled Meetings\n\n`;

  const byDate = {};
  for (const e of timed) {
    const date = e.start.slice(0, 10);
    (byDate[date] = byDate[date] || []).push(e);
  }
  for (const [date, events] of Object.entries(byDate).sort()) {
    const d = new Date(date + 'T12:00:00Z');
    md += `### ${d.toLocaleDateString('en-US', { weekday: 'long' })} ${date}\n`;
    for (const e of events) md += `- ${e.start.slice(11, 16)} — ${e.subj}\n`;
    md += `\n`;
  }

  writeWithPreservedEdits(path.join(sourcesDir, 'calendar.md'), md);
  console.log(`  [OK] ${allDay.length} all-day, ${timed.length} timed`);
}

function pollTeams(sourcesDir) {
  if (!TEAMS_CHAT) { console.log('[teams] Skipped (no teams-chat configured)'); return; }
  console.log('[teams] Polling Teams chats...');

  const targetsStr = JSON.stringify(TEAMS_TARGETS).replace(/"/g, "'");
  const script = `
import sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
sys.path.insert(0, '.')
from token_manager import graph_get
data = graph_get('/me/chats', params={'$top': 50, '$orderby': 'lastMessagePreview/createdDateTime desc'})
targets = ${JSON.stringify(TEAMS_TARGETS)}
for c in data.get('value', []):
    t = c.get('topic') or ''
    for k, v in targets.items():
        if k.lower() in t.lower():
            print(f'{c["id"]}|||{v}|||{t}')
            break
`;
  const chatMap = pythonQuery(script);
  if (!chatMap.trim()) return;

  const seen = new Set();
  for (const line of chatMap.trim().split('\n')) {
    if (!line.includes('|||')) continue;
    const [chatId, slug, topic] = line.split('|||');
    if (seen.has(slug)) continue; // dedupe (e.g. multiple Panavision chats)
    seen.add(slug);

    console.log(`  [teams] Reading ${slug}...`);
    try {
      const output = execSync(
        `python "${TEAMS_CHAT}" read "${chatId}" --limit 25`,
        { encoding: 'utf-8', timeout: 15000, env: { ...process.env, PYTHONIOENCODING: 'utf-8' } }
      );
      let md = `# Teams: ${topic}\nLast polled: ${new Date().toISOString().slice(0, 19)}\nChat ID: ${chatId}\n\n## Messages\n\n${output}\n\n## My takeaways\n\n<!-- Edit this section to correct my interpretation -->\n\n`;
      writeWithPreservedEdits(path.join(sourcesDir, `teams-${slug}.md`), md);
      console.log(`    [OK] ${slug}`);
    } catch (e) {
      console.error(`    [ERROR] ${slug}: ${e.message.slice(0, 100)}`);
    }
  }
}

function pollTranscripts(sourcesDir) {
  console.log('[transcripts] Scanning transcript reports...');
  const reportsDir = path.join(PROJECT_ROOT, 'reports');
  if (!fs.existsSync(reportsDir)) { console.log('  [SKIP] No reports/ directory'); return; }

  const monday = getMonday();
  const files = fs.readdirSync(reportsDir)
    .filter(f => f.endsWith('.md') && !f.startsWith('weekly-'))
    .filter(f => {
      const stat = fs.statSync(path.join(reportsDir, f));
      return stat.mtime >= new Date(monday + 'T00:00:00');
    });

  let md = `# Transcript Reports\nLast polled: ${new Date().toISOString().slice(0, 19)}\nReports this week: ${files.length}\n\n`;
  for (const f of files.sort()) {
    const dateMatch = f.match(/(\d{4}-\d{2}-\d{2})/);
    md += `## ${f.replace('.md', '')}\n**Meeting date:** ${dateMatch ? dateMatch[1] : 'unknown'}\n**Report file:** reports/${f}\n**Key takeaway:** \n\n---\n\n`;
  }
  fs.writeFileSync(path.join(sourcesDir, 'transcript-reports.md'), md);
  console.log(`  [OK] ${files.length} reports`);
}

function pollNotes(sourcesDir) {
  if (!NOTES_DIRS.length) { console.log('[notes] Skipped (no notesDirs configured)'); return; }
  console.log('[notes] Scanning handwritten notes...');

  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - 7);

  let md = `# Handwritten Notes\nLast polled: ${new Date().toISOString().slice(0, 19)}\n\n`;
  for (const dir of NOTES_DIRS) {
    if (!fs.existsSync(dir)) continue;
    md += `## ${path.basename(dir)}\n\n`;
    try {
      for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isFile()) {
          const stat = fs.statSync(fullPath);
          if (stat.mtime >= cutoff) md += `- ${fullPath}\n`;
        } else if (entry.isDirectory()) {
          try {
            for (const s of fs.readdirSync(fullPath, { withFileTypes: true })) {
              if (s.isFile()) {
                const sp = path.join(fullPath, s.name);
                if (fs.statSync(sp).mtime >= cutoff) md += `- ${sp}\n`;
              }
            }
          } catch (_) {}
        }
      }
    } catch (e) { md += `  (error: ${e.message.slice(0, 80)})\n`; }
    md += `\n`;
  }
  fs.writeFileSync(path.join(sourcesDir, 'handwritten-notes.md'), md);
  console.log(`  [OK]`);
}

// ─── Main ─────────────────────────────────────────────────────────

const args = process.argv.slice(2);
const dryRun = args.includes('--dry-run');
const sourceFilter = args.includes('--source') ? args[args.indexOf('--source') + 1] : null;
const sinceOverride = args.includes('--since') ? args[args.indexOf('--since') + 1] : null;
const since = sinceOverride || getMonday();

const weekDir = getWeekDir();
console.log(`[poll] Week: ${path.basename(weekDir)} | Since: ${since}`);

if (dryRun) {
  console.log('[dry-run] Would poll: emails, cases, calendar, teams, transcripts, notes');
  process.exit(0);
}

ensureDirs(weekDir);
const sourcesDir = path.join(weekDir, 'sources');

const polls = {
  'emails': () => pollSentEmails(sourcesDir, since),
  'cases': () => pollCaseUpdates(sourcesDir, since),
  'calendar': () => pollCalendar(sourcesDir),
  'teams': () => pollTeams(sourcesDir),
  'transcripts': () => pollTranscripts(sourcesDir),
  'notes': () => pollNotes(sourcesDir),
};

const toRun = sourceFilter ? { [sourceFilter]: polls[sourceFilter] } : polls;
for (const [name, fn] of Object.entries(toRun)) {
  if (!fn) { console.error(`[ERROR] Unknown source: ${name}`); continue; }
  try { fn(); } catch (e) { console.error(`[ERROR] ${name}: ${e.message}`); }
}

fs.writeFileSync(path.join(weekDir, '.last-poll'), new Date().toISOString());
console.log(`[done] ${path.basename(weekDir)}/sources/`);
