name: get_container_security_rulesets
description: Get ruleset details
method: GET
endpoint: /v3.0/containerSecurity/rulesets/{id}
template: single_get
tags:
- Rulesets
params:
  required: []
  optional: []
template_config: {}
