name: create_content_pagehierarchy_copy
description: Copy page hierarchy
method: POST
endpoint: /wiki/rest/api/content/{id}/pagehierarchy/copy
template: create
tags:
- Content - children and descendants
params:
  required:
  - name: id
    type: string
    description: 'Path parameter: id'
  optional: []
template_config: {}
