name: update_relation_from_to
description: Create relationship
method: PUT
endpoint: /wiki/rest/api/relation/{relationName}/from/{sourceType}/{sourceKey}/to/{targetType}/{targetKey}
template: update
tags:
- Relation
params:
  required:
  - name: relationName
    type: string
    description: 'Path parameter: relationName'
  - name: sourceType
    type: string
    description: 'Path parameter: sourceType'
  - name: sourceKey
    type: string
    description: 'Path parameter: sourceKey'
  - name: targetType
    type: string
    description: 'Path parameter: targetType'
  - name: targetKey
    type: string
    description: 'Path parameter: targetKey'
  optional: []
template_config: {}
