name: get_endpoint
endpoint: /v3.0/endpointSecurity/endpoints/{endpoint_id}
method: GET
template: single_get
description: Get endpoint details
params:
  required:
  - name: endpoint_id
    type: str
    description: Endpoint ID
  optional: []
template_config:
  pagination: null
  date_params: null
  filter_style: null
categories:
- endpoint_management
- agent_management
