name: list_search_activity_statistics
description: Query activity data statistics
method: GET
endpoint: /v3.0/search/activityStatistics
template: single_get
tags:
- Statistics
params:
  required: []
  optional:
  - name: period
    type: string
    description: 'The time period for the Trend Vision One connected product status.
      Default: 7 days.'
template_config: {}
