name: create_group_user_by_group_id
description: Add member to group by groupId
method: POST
endpoint: /wiki/rest/api/group/userByGroupId
template: create
tags:
- Group
params:
  required: []
  optional: []
template_config: {}
