name: delete_endpoint_security_endpoint_delete
description: Remove endpoints
method: POST
endpoint: /v3.0/endpointSecurity/endpoints/delete
template: post_action
tags:
- Endpoint Security
params:
  required: []
  optional: []
template_config: {}
