name: delete_content_restriction_by_operation_user
description: Remove user from content restriction
method: DELETE
endpoint: /wiki/rest/api/content/{id}/restriction/byOperation/{operationKey}/user
template: delete
tags:
- Content restrictions
params:
  required:
  - name: id
    type: string
    description: 'Path parameter: id'
  - name: operationKey
    type: string
    description: 'Path parameter: operationKey'
  optional: []
template_config: {}
