name: get_gcp_account
endpoint: /v3.0/cam/gcpProjects/{account_id}
method: GET
template: single_get
description: Get GCP project details
params:
  required:
  - name: account_id
    type: str
    description: GCP project number
  optional: []
template_config:
  pagination: null
  date_params: null
  filter_style: null
categories:
- cloud_security
- cloud_accounts
