name: case_management_cases_attachments
description: Add an attachment
method: POST
endpoint: /v3.0/caseManagement/cases/{id}/attachments
template: post_action
tags:
- Case
params:
  required:
  - name: id
    type: string
    description: The case ID
  optional: []
template_config: {}
